"""Python client for the Stash GraphQL API."""

from .client import StashClient
from .criteria import (
    between,
    equals,
    excludes,
    gql_criterion,
    greater_than,
    includes,
    includes_all,
    is_null,
    less_than,
    matches_regex,
    not_equals,
    not_matches_regex,
    not_null,
    stash_id,
    stash_ids,
)
from .errors import (
    GraphQLError,
    StashConnectionError,
    StashError,
    StashResponseError,
    TransportError,
)
from .filters import (
    find_filter,
    gallery_filter,
    group_filter,
    image_filter,
    marker_filter,
    performer_filter,
    scene_filter,
    studio_filter,
    tag_filter,
)
from .mutation import MutationPlan, prepare_mutations

__all__ = [
    "GraphQLError",
    "MutationPlan",
    "StashClient",
    "StashConnectionError",
    "StashError",
    "StashResponseError",
    "TransportError",
    "between",
    "equals",
    "excludes",
    "find_filter",
    "gallery_filter",
    "gql_criterion",
    "greater_than",
    "group_filter",
    "image_filter",
    "includes",
    "includes_all",
    "is_null",
    "less_than",
    "marker_filter",
    "matches_regex",
    "not_equals",
    "not_matches_regex",
    "not_null",
    "performer_filter",
    "prepare_mutations",
    "scene_filter",
    "stash_id",
    "stash_ids",
    "studio_filter",
    "tag_filter",
]
